[project]
name = "opcua-cert"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cryptography>=46.0.1",
    "prompt-toolkit>=3.0.52",
]

[project.scripts]
opcua-cert = "src.opcua_certificate_tui:main"

